import { existsSync, promises as fs } from 'node:fs';
import { join, relative, sep } from 'node:path';
import type { CheckpointRouteRecord } from './types';

export interface EntrypointGeneratorOptions {
  version: string;
  outputDir: string;
  routesDir: string;
  socketPath: string;
}

export class CheckpointEntrypointGenerator {
  private discoveredRoutes: CheckpointRouteRecord[] = [];

  async generate(options: EntrypointGeneratorOptions): Promise<string> {
    const routeFiles = await this.scanRouteFiles(options.routesDir);
    const source = this.buildSource(routeFiles, options);

    const outputPath = join(options.outputDir, 'entrypoint.ts');
    await fs.writeFile(outputPath, source, 'utf-8');
    return outputPath;
  }

  getDiscoveredRoutes(): CheckpointRouteRecord[] {
    return this.discoveredRoutes;
  }

  private async scanRouteFiles(routesDir: string): Promise<string[]> {
    if (!existsSync(routesDir)) {
      return [];
    }

    const files: string[] = [];
    await this.walkDir(routesDir, files);
    return files;
  }

  private async walkDir(dir: string, files: string[]): Promise<void> {
    const entries = await fs.readdir(dir);

    for (const entry of entries) {
      const fullPath = join(dir, entry);
      const stats = await fs.stat(fullPath);

      if (stats.isDirectory()) {
        await this.walkDir(fullPath, files);
      } else if (
        (entry.endsWith('.ts') || entry.endsWith('.js')) &&
        !entry.endsWith('.test.ts') &&
        !entry.endsWith('.test.js') &&
        !entry.endsWith('.spec.ts') &&
        !entry.endsWith('.spec.js') &&
        !entry.endsWith('.d.ts')
      ) {
        files.push(fullPath);
      }
    }
  }

  private buildSource(routeFiles: string[], options: EntrypointGeneratorOptions): string {
    this.discoveredRoutes = [];

    const imports: string[] = [];
    const registrations: string[] = [];

    for (const [i, file] of routeFiles.entries()) {
      const varName = `routeModule_${i}`;
      imports.push(`import * as ${varName} from '${file}';`);
      registrations.push(`  registerModule(${varName});`);

      // Record discovered route for manifest
      const routePath = relative(options.routesDir, file)
        .replace(/\.(ts|js)$/, '')
        .split(sep)
        .join('/');

      this.discoveredRoutes.push({
        method: '*',
        path: `/${routePath}`,
      });
    }

    return `// Checkpoint entrypoint — auto-generated for version ${options.version}
// DO NOT EDIT: This file is generated by Vector checkpoint publish.

${imports.join('\n')}

const socketPath = process.env.VECTOR_CHECKPOINT_SOCKET ?? '${options.socketPath}';
const checkpointContextHeader = 'x-vector-checkpoint-context';

// Route registration helper
type RouteDefinition = {
  entry: { method: string; path: string };
  options: { method: string; path: string; [key: string]: any };
  handler: (ctx: any) => any;
};

function isRouteDefinition(value: unknown): value is RouteDefinition {
  return (
    value !== null &&
    typeof value === 'object' &&
    'entry' in value &&
    'options' in value &&
    'handler' in value &&
    typeof (value as any).handler === 'function'
  );
}

const routeTable: Record<string, Record<string, (req: Request) => Response | Promise<Response>>> = {};

function parseCheckpointContext(req: Request): Record<string, unknown> {
  const encoded = req.headers.get(checkpointContextHeader);
  if (!encoded) {
    return {};
  }

  try {
    const json = Buffer.from(encoded, 'base64url').toString('utf-8');
    const parsed = JSON.parse(json);
    if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
      return {};
    }
    return parsed as Record<string, unknown>;
  } catch {
    return {};
  }
}

function parseQuery(url: URL): Record<string, string | string[]> {
  const query: Record<string, string | string[]> = {};
  for (const [key, value] of url.searchParams) {
    if (key in query) {
      const existing = query[key];
      if (Array.isArray(existing)) {
        existing.push(value);
      } else {
        query[key] = [existing as string, value];
      }
    } else {
      query[key] = value;
    }
  }
  return query;
}

function parseCookies(cookieHeader: string | null): Record<string, string> {
  const cookies: Record<string, string> = {};
  if (!cookieHeader) {
    return cookies;
  }
  for (const pair of cookieHeader.split(';')) {
    const idx = pair.indexOf('=');
    if (idx > 0) {
      cookies[pair.slice(0, idx).trim()] = pair.slice(idx + 1).trim();
    }
  }
  return cookies;
}

function extractRouteParams(req: Request): Record<string, string> {
  const nativeParams = (req as Request & { params?: Record<string, string> }).params;
  if (nativeParams && typeof nativeParams === 'object' && !Array.isArray(nativeParams)) {
    return nativeParams;
  }
  return {};
}

function createContext(req: Request): Record<string, unknown> {
  const ctx: Record<string, unknown> = Object.create(null);
  setContextField(ctx, 'request', req);

  // Initialize always-present VectorContext fields with defaults derived from the request
  setContextField(ctx, 'params', extractRouteParams(req));

  try {
    setContextField(ctx, 'query', parseQuery(new URL(req.url)));
  } catch {
    setContextField(ctx, 'query', {});
  }

  setContextField(ctx, 'cookies', parseCookies(req.headers.get('cookie')));
  setContextField(ctx, 'metadata', {});

  const checkpointContext = parseCheckpointContext(req);
  const allowedCheckpointKeys = ['metadata', 'content', 'validatedInput', 'authUser'] as const;
  for (const key of allowedCheckpointKeys) {
    if (!Object.prototype.hasOwnProperty.call(checkpointContext, key)) {
      continue;
    }
    const value = checkpointContext[key];
    setContextField(ctx, key, value);
  }

  return ctx;
}

function setContextField(target: Record<string, unknown>, key: string, value: unknown) {
  const ownDescriptor = Object.getOwnPropertyDescriptor(target as object, key);
  if (ownDescriptor && ownDescriptor.writable === false && typeof ownDescriptor.set !== 'function') {
    return;
  }

  try {
    target[key] = value;
    return;
  } catch {
    // Fall back to own-property define when inherited Request field is readonly.
  }

  try {
    Object.defineProperty(target, key, {
      value,
      writable: true,
      configurable: true,
      enumerable: true,
    });
  } catch {
    // Ignore non-extensible context edge cases.
  }
}

function addToRouteTable(method: string, path: string, handler: (ctx: any) => any) {
  if (!routeTable[path]) {
    routeTable[path] = Object.create(null);
  }
  routeTable[path][method.toUpperCase()] = async (req: Request) => {
    const ctx = createContext(req);
    const result = await handler(ctx);
    if (result instanceof Response) return result;
    return Response.json(result);
  };
}

function registerModule(mod: Record<string, unknown>) {
  for (const [name, value] of Object.entries(mod)) {
    if (isRouteDefinition(value)) {
      addToRouteTable(value.options.method, value.options.path, value.handler);
    } else if (name === 'default' && typeof value === 'function') {
      // Default export functions need path context — skip for now
    }
  }
}

${registrations.join('\n')}

// Health check endpoint for parent process
routeTable['/_vector/health'] = {
  GET: () => Response.json({ status: 'ok', version: '${options.version}' }),
};

const server = Bun.serve({
  unix: socketPath,
  routes: routeTable,
  fetch(req: Request) {
    return Response.json(
      { error: true, message: 'Not Found', statusCode: 404 },
      { status: 404 }
    );
  },
});

// Signal readiness to parent process
process.stdout.write('READY\\n');
`;
  }
}
