name: CI

on:
  push:
    branches: ['**']
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/workflows/publish.yml'
  pull_request:
    branches: ['**']
    paths-ignore:
      - '**.md'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install
      
      - name: Lint code
        run: bun run lint
      
      - name: Check formatting
        run: bun run format:check
      
      - name: Type check
        run: bun run typecheck
  
  test:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        # Windows excluded due to Bun CI compatibility issues
    
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install
      
      - name: Run tests
        run: bun test
      
      - name: Generate coverage report
        if: matrix.os == 'ubuntu-latest'
        run: bun test:coverage
      
      - name: Upload coverage
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
  
  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: [lint, test]
    
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install
      
      - name: Build
        run: bun run build:lib
      
      - name: Run E2E tests
        run: bun run test:e2e
      
      - name: Performance tests
        run: |
          bun run test:benchmark || true
          bun run test:load || true
        continue-on-error: true
  
  docker:
    name: Docker Build & Test
    runs-on: ubuntu-latest
    needs: [lint]
    
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      
      - name: Build Docker image
        run: docker build -t vector:ci .
      
      - name: Build test image
        run: docker build -t vector:test --target test .
      
      - name: Run Docker tests
        run: |
          docker-compose -f docker-compose.test.yml run test-unit
          docker-compose -f docker-compose.test.yml run test-e2e
  
  build:
    name: Build Distribution
    runs-on: ubuntu-latest
    needs: [lint, test]
    
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install
      
      - name: Build library
        run: bun run build:lib
      
      - name: Check build output
        run: |
          ls -la dist/
          test -f dist/index.js
          test -f dist/index.mjs
          test -f dist/index.d.ts
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 7
  
  status:
    name: CI Status
    runs-on: ubuntu-latest
    needs: [lint, test, e2e, docker, build]
    if: always()
    
    steps:
      - name: Check status
        run: |
          if [[ "${{ needs.lint.result }}" == "failure" || \
                "${{ needs.test.result }}" == "failure" || \
                "${{ needs.e2e.result }}" == "failure" || \
                "${{ needs.docker.result }}" == "failure" || \
                "${{ needs.build.result }}" == "failure" ]]; then
            echo "CI failed"
            exit 1
          fi
          echo "CI passed successfully!"